name: Icarus Simulation

on:
  push:
    branches:
      - "**"   # odpalaj na każdej gałęzi
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Build simulation
        run: |
          rm -f sim.out
          iverilog -g2012 -o sim.out ttt_v2.sv ttt_tb_v2.sv

      - name: Run simulation
        run: vvp sim.out

